import React from 'react';

const Preparation = () => {
    return (
        <div>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi animi esse, incidunt odio veniam mollitia blanditiis accusamus eius et, non obcaecati, magnam earum amet. Magnam, deserunt incidunt, voluptatibus reiciendis accusantium ipsum eaque odio veritatis inventore eveniet odit tenetur. Animi repudiandae magnam esse doloremque natus repellat, magni cupiditate officia dicta cum laborum asperiores aut harum voluptates maiores incidunt nulla. Rem, nulla quisquam sunt non consequatur repudiandae rerum fuga esse iusto commodi voluptates veritatis ea unde autem quis placeat fugit expedita obcaecati accusantium at culpa eligendi harum officia. Odit nesciunt, reiciendis nam quisquam doloremque animi tenetur sed! Cupiditate repellendus, quam veniam blanditiis deserunt qui tenetur a harum laudantium libero quis, molestiae ipsam quos id quas optio ullam eos deleniti quisquam alias magnam ducimus voluptates! Minima alias saepe eaque autem. Provident, aut accusantium architecto sapiente cum quia, esse tempora autem doloremque eum ex. Similique architecto unde iure nostrum repellendus placeat, eveniet omnis corrupti magnam maiores nisi beatae excepturi suscipit ea quisquam, id veniam! Ipsa tenetur quisquam, expedita esse fuga nisi vel in. Cupiditate, a beatae iure consequuntur praesentium officia distinctio nisi sint nesciunt architecto minima, aut minus hic quod vel ducimus quia eaque blanditiis deserunt consectetur, tempora ab quaerat iste eligendi. Harum nulla repellendus, vero corporis laudantium beatae soluta cumque quae maxime magnam, unde, explicabo veritatis necessitatibus dolorum fuga architecto aut dolore consequuntur! Omnis fugit temporibus veniam beatae, minima explicabo perspiciatis, repudiandae quae consectetur cupiditate, iste asperiores perferendis. Quisquam consectetur asperiores magnam nihil minus inventore porro dolore mollitia nam nobis. Laboriosam, inventore nam. Eius amet magni vel. Ut quaerat veritatis impedit temporibus explicabo nam voluptatibus vero libero eaque, voluptatem facere labore pariatur perspiciatis consequatur, qui non nostrum nulla voluptas fugit quasi ipsum est. Rerum asperiores earum ipsum minus ipsa, excepturi eligendi neque porro nam unde in nihil obcaecati quos sequi expedita rem at.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi atque nemo sed non. Quo esse voluptatibus ipsa fugiat, quas eius soluta laborum minima iusto dolores perferendis quos atque, dolor veritatis vero! Ipsa quis aliquid ipsam quia dolor illo possimus neque eos laboriosam nesciunt! Aut veritatis veniam molestias, possimus doloremque blanditiis animi accusamus repudiandae quidem magnam porro in, ipsam incidunt voluptate beatae perferendis nostrum ea ab! Ullam officia fuga laudantium rerum natus dolor repellendus, harum deserunt placeat? Deleniti, sit eius atque perferendis nobis esse ipsam quod tempore? Molestiae cum repellendus reiciendis impedit, pariatur voluptatem, maxime ex rerum vitae illum, maiores assumenda!</p>
        </div>
    );
};

export default Preparation;