import React from 'react';

const Video = () => {
    return (
        <div className='text-justify'>
            <h2 className='uppercase text-xl'>Teaching Video series will be uploaded here</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet maiores, quo dolore atque suscipit deleniti reprehenderit architecto quam, consequatur repellendus sit ipsa voluptates laudantium incidunt voluptatum qui officia alias temporibus tempora. Dicta ea eligendi quo accusantium ad eos id alias animi porro saepe? Pariatur aut amet iste quo earum facere eos nihil deserunt, alias quisquam ullam, quas iusto laboriosam id? Autem, officiis mollitia? Vero nam fugiat consequatur quod est, pariatur suscipit laborum fuga labore, accusantium modi minima nisi omnis autem dolor facere enim error consequuntur earum. Sequi dolorem optio, consequuntur molestias nihil at dolor. Magnam neque eos veniam a iusto.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet maiores, quo dolore atque suscipit deleniti reprehenderit architecto quam, consequatur repellendus sit ipsa voluptates laudantium incidunt voluptatum qui officia alias temporibus tempora. Dicta ea eligendi quo accusantium ad eos id alias animi porro saepe? Pariatur aut amet iste quo earum facere eos nihil deserunt, alias quisquam ullam, quas iusto laboriosam id? Autem, officiis mollitia? Vero nam fugiat consequatur quod est, pariatur suscipit laborum fuga labore, accusantium modi minima nisi omnis autem dolor facere enim error consequuntur earum. Sequi dolorem optio, consequuntur molestias nihil at dolor. Magnam neque eos veniam a iusto.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet maiores, quo dolore atque suscipit deleniti reprehenderit architecto quam, consequatur repellendus sit ipsa voluptates laudantium incidunt voluptatum qui officia alias temporibus tempora. Dicta ea eligendi quo accusantium ad eos id alias animi porro saepe? Pariatur aut amet iste quo earum facere eos nihil deserunt, alias quisquam ullam, quas iusto laboriosam id? Autem, officiis mollitia? Vero nam fugiat consequatur quod est, pariatur suscipit laborum fuga labore, accusantium modi minima nisi omnis autem dolor facere enim error consequuntur earum. Sequi dolorem optio, consequuntur molestias nihil at dolor. Magnam neque eos veniam a iusto.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet maiores, quo dolore atque suscipit deleniti reprehenderit architecto quam, consequatur repellendus sit ipsa voluptates laudantium incidunt voluptatum qui officia alias temporibus tempora. Dicta ea eligendi quo accusantium ad eos id alias animi porro saepe? Pariatur aut amet iste quo earum facere eos nihil deserunt, alias quisquam ullam, quas iusto laboriosam id? Autem, officiis mollitia? Vero nam fugiat consequatur quod est, pariatur suscipit laborum fuga labore, accusantium modi minima nisi omnis autem dolor facere enim error consequuntur earum. Sequi dolorem optio, consequuntur molestias nihil at dolor. Magnam neque eos veniam a iusto.</p>
        </div>
    );
};

export default Video;